slam_toolbox:
  ros__parameters:

    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan


    resolution: 0.05
    map_start_resolution: 0.1
    map_start_size: 1024


    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG


    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    minimum_time_interval: 0.5


    throttle_scans: 1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0


    loop_search_maximum_distance: 10.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45


    map_update_interval: 5.0
    enable_interactive_mode: true